### ISSUE TITLE
Add curl for simple healthchecks

### ISSUE THREAD

**Issue by madmath03** [CollaboraOnline/Docker-CODE#100]
Add `curl` to docker image.

This would allow to setup simple healthchecks in docker-compose:
```yml
version: "2.3"

services:
  collabora:
    image: collabora/code:4.2.5.3
    hostname: collabora
    domainname: ${DOMAIN}
    container_name: collabora
    restart: always
    # Simple healthcheck
    healthcheck:
      test: curl --fail http://127.0.0.1:9980/ | grep -q -e 'OK' || exit 1
      interval: 60s
      timeout: 10s
      #start_period: 5s
      retries: 4
    cap_add:
      - MKNOD
    ports:
      - "9980:9980"
    environment:
      - domain=cloud.${DOMAIN}
      - server_name=collabora.${DOMAIN}
      - username=${COLLABORA_ADMIN_USER}
      - password=${COLLABORA_ADMIN_PWD}
      #- extra_params=
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

```
