### ISSUE TITLE
Linking/Copying files from /opt/lool/systemplate is taking too much time

### ISSUE THREAD

**Issue by leoc** [CollaboraOnline/Docker-CODE#32]
Running the container with nginx-letsencryptproxy via:

```
  collabora:
    image: collabora/code
    ports:
      - 9980:9980
    restart: always
    container_name: collabora
    environment:
      - VIRTUAL_HOST=collabora.domain
      - VIRTUAL_NETWORK=webproxy
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=collabora.domain
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - domain=collabora.domain
    cap_add:
      - MKNOD
```

Just prints on the logs:

```
kit-00031-00029 12:39:16.968699 [ loolkit ] WRN  Linking/copying files from /opt/lool/systemplate to /opt/lool/child-roots/rdazZ2ks5jp2ON3p/ is taking too much time. Enabling verbose link/copy logging at information level.| kit/Kit.cpp:163
```
