### ISSUE TITLE
[ loolkit ] WRN  Waking up dead poll thread [kit], started: false, finished: false| ./net/Socket.hpp:550

### ISSUE THREAD

**Issue by krueuw** [CollaboraOnline/Docker-CODE#37]
CODE 3.0.0 without problems, 
since update to 3.3.1 it stable dont work with the same docker-compose.yml 

`[ loolkit ] WRN  Waking up dead poll thread [kit], started: false, finished: false| ./net/Socket.hpp:550
`
```
version: 2
services:
  office:
    image: collabora/code
    restart: always
    expose:
      - 9980
    cap_add:
      - MKNOD
    environment:
      - domain=owncloud\\.xy\\.de
      - VIRTUAL_NETWORK=nginxproxy_default
      - VIRTUAL_PORT=9980
      - VIRTUAL_PROTO=https
      - VIRTUAL_HOST=office.xy.de
      - LETSENCRYPT_HOST=office.xy.de
      - LETSENCRYPT_EMAIL=webadmin@xy.de
    networks:
      - nginxproxy_default

networks:
  nginxproxy_default:
     external: true
```
