### ISSUE TITLE
rancer load balancer instead of proxy?

### ISSUE THREAD

**Issue by MSandro** [CollaboraOnline/Docker-CODE#42]
Hi I am use Rancher to manage my Containers via Kubernetes. Nextcloud and Onlyoffice work fine via Level 7 load balancer and Lets Encrypt cert. But I am not able to setup Collabora office. Does anyon use Collabora on Rancher?

`Generating RSA private key, 2048 bit long modulus
...+++
.........+++
e is 65537 (0x10001)
Generating RSA private key, 2048 bit long modulus
........................+++
..+++
e is 65537 (0x10001)
Signature ok
subject=/C=DE/ST=BW/L=Stuttgart/O=Dummy Authority/CN=localhost
Getting CA Private Key
loolforkit version details: 3.3.1 - 0adc773
Init vcl
preload: merged unordf ucpchelp1 msforms vbaobj pcr vbaswobj sw animcore hwp flash chartcore solver sc wpftcalc xof ucpcmis1 wpftdraw sd svgfilter evtatt ucpftp1 graphicfilter wpftimpress placeware sdfilt sm pdffilter PresentationMinimizer rptxml protocolhandler ucpdav1 wpftwriter msword lwpft writerfilter t602filter xmlfa basctl binaryurp uuresolver scd chartcontroller ldapbe2 dba sdbt dbu dbmm deploymentgui migrationoo2 migrationoo3 xsltfilter sdd embobj emboleobj log expwrap odfflatxml textfd storagefd xmlfd frm fwl fwm io textconversiondlgs smd mozbootstrap oox scfilt OGLTrans slideshow proxyfac cairocanvas vclcanvas canvasfactory mtfrenderer simplecanvas oglcanvas rptui rpt res dlgprov basprov stringresource dbaxml mork odbc sdbc2 calc dbase flat writer xsec_xmlsec reflection bootstrap introspection invocation invocadapt namingservice stocservices cmdmail syssh cached1 ucphier1 ucpimage ucppkg1 srtrs1 ucptdoc1 xsltdlg swd cui bib guesslang offacc scn scriptframe dbpool2 xmlsecurity analysis date pricing fps_office i18nsearch wizards.agenda.CallWizard wizards.fax.CallWizard wizards.letter.CallWizard wizards.web.CallWizard xsec_fw vbaevents PresenterScreen pdfimport abp dbp mysql ucpext hyphen spell lnth mailmerge for ctl passwordcontainer svgio updatefeed
Preloading dictionaries: Whitelisted languages: de_DE en_GB en_US es_ES fr_FR it nl pt_BR pt_PT ru
de_DE en_US fr_FR it_IT nl_NL pt_BR ru_RU en_GB nl_BE pt_PT es_ES
Preloading thesauri: de_DE en_US fr_FR it_IT nl_NL pt_BR ru_RU en_GB nl_BE pt_PT es_ES
Preload icons
Preload languages
kit-00036-00030 2018-09-07 20:43:30.436424 [ loolkit ] WRN Linking/copying files from /opt/collaboraoffice5.3 to /opt/lool/child-roots/lLqPWoi1yAMHeg6b/lo/ is taking too much time. Enabling verbose link/copy logging at information level.| kit/Kit.cpp:163
office version details: { "ProductName": "Collabora Office", "ProductVersion": "5.3", "ProductExtension": ".10.53", "BuildId": "cf2ac11617bce9c49c92d8153ef12b55e5b903f3" }
kit-00036-00030 2018-09-07 20:48:16.665625 [ loolkit ] WRN Waking up dead poll thread [kit], started: false, finished: false| ./net/Socket.hpp:550
wsd-00028-00029 2018-09-07 20:48:16.665950 [ prisoner_poll ] WRN ForKit not responsive for 310057 ms forking 1 children. Resetting.| wsd/LOOLWSD.cpp:385
kit-00042-00030 2018-09-07 20:48:17.626988 [ loolkit ] WRN Waking up dead poll thread [kit], started: false, finished: false| ./net/Socket.hpp:550
wsd-00028-00040 2018-09-07 20:49:27.736297 [ websrv_poll ] ERR Socket #21 SSL BIO error: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request (errno: Success)| ./net/SslSocket.hpp:281
wsd-00028-00040 2018-09-07 20:49:27.736651 [ websrv_poll ] ERR Error while handling poll for socket #21 in websrv_poll: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request| ./net/Socket.hpp:517
wsd-00028-00040 2018-09-07 20:49:27.895007 [ websrv_poll ] ERR Socket #21 SSL BIO error: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request (errno: Success)| ./net/SslSocket.hpp:281
wsd-00028-00040 2018-09-07 20:49:27.895227 [ websrv_poll ] ERR Error while handling poll for socket #21 in websrv_poll: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request| ./net/Socket.hpp:517`

I am not 100 % sure if this is realy an failuere my SSL configuration but hope someon could help me.
Thank you very much

**Comment by tobiasbaehr** [comment]
In your loolwsd.xml set the following:

```
<ssl desc="SSL settings">
<enable type="bool" default="true">false</enable>
<termination desc="Connection via proxy where loolwsd acts as working via https, but actually uses http." type="bool" default="true">true</termination>
.....
</ssl>
```

**Comment by chrisingenhaag** [comment]
Hi @MSandro, 
I also use rancher and got this to work.
@tobiasbaehr is right. You have to tell the application that you´re using ssl termination. But you can handle this via environment variables in kubernetes/rancher.

```- env:
        - name: dictionaries
          value: de_DE en_GB en_US
        - name: domain
          value: nextcloud\\.yourdomain\\.com
        - name: extra_params
          value: --o:ssl.termination=true --o:ssl.enable=false
        - name: password
          value: secretpassword982
        - name: server_name
          value: collabora\.yourdomain\.com
        - name: username
          value: admin
```

Pay attention on the two domain values there. For me domain has to be double-escaped, but server_name single-escaped. In front of the deployment I also have an nginx ingress with lets-encrypt certificate.

see complete deployment.yaml here

```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-collabora
  name: collabora
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-collabora
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-collabora
    spec:
      containers:
      - env:
        - name: dictionaries
          value: de_DE en_GB en_US
        - name: domain
          value: nextcloud\\.yourdomain\\.com
        - name: extra_params
          value: --o:ssl.termination=true --o:ssl.enable=false
        - name: password
          value: your specialsecret
        - name: server_name
          value: collabora\.yourdomain\.com
        - name: username
          value: admin
        image: collabora/code
        imagePullPolicy: Always
        name: collabora
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - MKNOD
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
      restartPolicy: Always
```
