### ISSUE TITLE
Secrets not working

### ISSUE THREAD

**Issue by wilfriedwolf** [CollaboraOnline/Docker-CODE#52]
If I pass admin user and password via env-variables everything works.
If I try passing these two variables via docker secrets, startup fails with the followin log:

```
Generating RSA private key, 2048 bit long modulus
...+++
........+++
e is 65537 (0x10001)
Generating RSA private key, 2048 bit long modulus
...+++
......................................................+++
e is 65537 (0x10001)
Signature ok
subject=/C=DE/ST=BW/L=Stuttgart/O=Dummy Authority/CN=localhost
Getting CA Private Key
Illegal division by zero at -e line 1, <> line 1.
Setting up watches.
Watches established.
SAXParseException: No element found in '/etc/loolwsd/loolwsd.xml', line 1 column 0
-00028 2018-12-18 10:15:40.541515 [ loolwsd ] WRN  Waking up dead poll thread [delay_poll], started: false, finished: false| ./net/Socket.hpp:551
-00028 2018-12-18 10:15:40.541552 [ loolwsd ] WRN  Waking up dead poll thread [delay_poll], started: false, finished: false| ./net/Socket.hpp:551
<shutdown>-00028 2018-12-18 10:15:40.541602 [ loolwsd ] WRN  Waking up dead poll thread [accept_poll], started: false, finished: false| ./net/Socket.hpp:551
<shutdown>-00028 2018-12-18 10:15:40.541613 [ loolwsd ] WRN  Waking up dead poll thread [accept_poll], started: false, finished: false| ./net/Socket.hpp:551
<shutdown>-00028 2018-12-18 10:15:40.541619 [ loolwsd ] WRN  Waking up dead poll thread [websrv_poll], started: false, finished: false| ./net/Socket.hpp:551
<shutdown>-00028 2018-12-18 10:15:40.541628 [ loolwsd ] WRN  Waking up dead poll thread [websrv_poll], started: false, finished: false| ./net/Socket.hpp:551
<shutdown>-00028 2018-12-18 10:15:40.541634 [ loolwsd ] WRN  Waking up dead poll thread [accept_poll], started: false, finished: false| ./net/Socket.hpp:551
<shutdown>-00028 2018-12-18 10:15:40.541642 [ loolwsd ] WRN  Waking up dead poll thread [accept_poll], started: false, finished: false| ./net/Socket.hpp:551
<shutdown>-00028 2018-12-18 10:15:40.541650 [ loolwsd ] WRN  Waking up dead poll thread [prisoner_poll], started: false, finished: false| ./net/Socket.hpp:551
<shutdown>-00028 2018-12-18 10:15:40.541659 [ loolwsd ] WRN  Waking up dead poll thread [prisoner_poll], started: false, finished: false| ./net/Socket.hpp:551
<shutdown>-00028 2018-12-18 10:15:40.541667 [ loolwsd ] WRN  Waking up dead poll thread [websrv_poll], started: false, finished: false| ./net/Socket.hpp:551
<shutdown>-00028 2018-12-18 10:15:40.541674 [ loolwsd ] WRN  Waking up dead poll thread [websrv_poll], started: false, finished: false| ./net/Socket.hpp:551
```

I am using docker swarm on digital ocean and I am trying to deploy the following `docker-compose.yml`:

```
 [...]
app:
  [...]
  office:
     build: ./office
     restart: always
     env_file:
       - ./office/office.env
     cap_add:
       - MKNOD
     volumes:
       - nextcloud:/var/www/html
       - nextcloud.data:/var/www/data
     secrets:
       - office_admin_user
       - office_admin_password
     ports:
       - 9980:9980
     depends_on:
       - app
[...]
secrets:
 [...]
 office_admin_user:
    file: ./office/office_admin_user.txt
  office_admin_password:
    file: ./office/office_admin_password.txt
```

If I use office.env as

```
domain=[...]
username=admin
password=admin123
```

everything is fine, if I do

```
domain=[...]
username=/run/secrets/office_admin_user
password=/run/secrets/office_admin_password

```

the above mentioned errors occur.

Any ideas?

Best regars and thanks,

Willi
