### ISSUE TITLE
Docker Image is filling up disk space within minutes

### ISSUE THREAD

**Issue by rmeissn** [CollaboraOnline/Docker-CODE#79]
I'm using the following docker image of collabora code - https://hub.docker.com/layers/collabora/code/latest/images/sha256-a309ee235d4e9d66c69462f2b73fcedd70d67bf07c436835d8541d8b0c1b6856
It's version 4.2.0.3, uploaded at 11. January 2020.

When running it, the container grows in size very quickly and fills my 100GB root filesystem within a few minutes. E.g. see the following output (I stopped it before filling my root filesystem):

`docker ps -a --size`
```
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS                        PORTS                                      NAMES                     SIZE
...                 collabora/code                           "/bin/sh -c 'bash st…"   5 minutes ago      Exited (137) 34 seconds ago                                              nextcloud-office          25.7GB (virtual 27.1GB)
```

This hasn't happened with the previous images (that I unfortunately deleted as of the update process) and happens for all version 4.2 images. I even deleted the container and also `/var/lib/docker` directory and set everything up from scratch by using the following compose snippet:

```
nextcloud-office:
    image: collabora/code
    restart: unless-stopped
    container_name: nextcloud-office
    environment:
      - VIRTUAL_HOST=...
      - VIRTUAL_PORT=9980
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_EMAIL=...
      - LETSENCRYPT_HOST=...
      - server_name=...
      - domain=...
      - dictionaries=de_DE en_GB
    cap_add:
      - MKNOD
    expose:
      - 9980
    networks:
      - reverse-proxy
```

I guess the images on dockerhub have some kind of bug. The log output is very long. I've added the last ~200 lines. See 
[logs.txt](https://github.com/CollaboraOnline/Docker-CODE/files/4086954/logs.txt)

I'm using Ubuntu 18.04 Server (updated), docker 18.09.7 from the official repos with overlay2 driver (which worked perfectly fine before).
If collabora code is running I am able to open documents in my nextcloud until collabora filled the hdd and Nextcloud refuses to work because of the full hdd.
