### ISSUE TITLE
Latest container fails to start with self signed certificates

### ISSUE THREAD

**Issue by mpibpc-mroose** [CollaboraOnline/Docker-CODE#84]
When I try to start collabora with 

```
collabora:
    image: collabora/code
    restart: always
    container_name: collabora
    ports:
      - 127.0.0.1:9980:9980
    environment:
      domain: 'example\\.com'
      dictionaries: 'de en'
      username: fooadmin
      password: P@ssword
    cap_add:
      - MKNOD

````
I get the output

 ```
collabora     | ..+++++
collabora     | e is 65537 (0x010001)
collabora     | Can't load /opt/lool/.rnd into RNG
collabora     | 140325070082496:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/opt/lool/.rnd
collabora     | Extra arguments given.
collabora     | genrsa: Use -help for summary.
```
There seems to be some problem with a parent image.

With image 4.2.0.3 all is fine 4.2.0.4 is broken.
